config/routes.rb
CalendarApp::Application.routes.draw do

  get "calendars/new"

  get "events/new"

  get "users/new"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :calendars
  resources :events, only: [:create, :edit, :update, :destroy]
  resources :subscriptions
 
  root to: 'static_pages#home'

  match '/events',  to: 'events#create'
  match '/calendars',  to: 'calendars#create'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/calendarcheck', to: 'calendars#check'
  match '/subscriptioncheck', to: 'subscriptions#check'
  match '/usercheck', to: 'users#check'
  match '/userverify', to: 'users#verify'
  match '/usersearch', to: 'users#search'

end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
    extend Enumerize
    enumerize :color, in: {blue: 0, red: 1, orange: 2, yellow: 3,
                           green: 4, purple: 5, brown: 6}, default: :blue

    attr_accessible :default, :title, :description, :color, :displayed, :public

    belongs_to :user
    has_many :events, dependent: :destroy
    has_many :subscriptions, dependent: :destroy

    validates :user_id, presence: true
    validates :title, presence: true
    validates :color, presence: true
    validates :default, :inclusion => { :in => [true, false] }
    validates_uniqueness_of :title, scope: [:user_id]
end

app/controllers/calendars_controller.rb
# This class is a rails controller for calendar objects
# Author::    Mark Grebe  
# Copyright:: Copyright (c) 2013 Mark Grebe
# License::   Distributes under the same terms as Ruby
# Developed for Master of Engineering Project
# University of Colorado - Boulder - Spring 2013
class CalendarsController < ApplicationController
  before_filter :signed_in_user
  before_filter :correct_user, only: [:edit, :show, :update]
  
  # Start creating a new calendar
  def new
    @calendar = Calendar.new
    @calendar.title = ""
  end

  # Save a new calendar
  def create
    @calendar = Calendar.new(params[:calendar])
    @calendar.user_id = current_user.id
    @calendar.default = false
    if @calendar.save
        redirect_to request.referer
    else
        flash[:error] = "Duplicate Calendar Title Not Allowed!"  
        redirect_to request.referer
    end
  end

  # Setup to edit a calendar
  def edit
    @calendar = Calendar.find_by_id(params[:id])
    respond_to do |format|
        format.html
        format.js 
    end
  end

  # Handle user clicking to show or not show a calendar
  def show
    @calendar = Calendar.find_by_id(params[:id])
    @calendar.displayed = params[:displayed]
    if @calendar.save
        redirect_to request.referer
    else
        flash[:error] = "Error showing/hiding calendar!"  
        redirect_to request.referer
    end
  end

  # Update an edited calendar
  def update
    @calendar = Calendar.find_by_id(params[:id])
    if @calendar.update_attributes(params[:calendar])
      redirect_to request.referer
    else
      flash[:error] = "Calendar update failed!"  
      redirect_to request.referer
    end
  end
 
  # Delete a calendar
  def destroy
    @calendar = Calendar.find_by_id(params[:id])
    @calendar.destroy
    redirect_to request.referer
  end

  # Utility AJAX method used to determine if calendar title is unique
  def check
    id = params[:calcheck].split('/').last.to_i
    cal = Calendar.where(id: id)
    # For invalid calendars or unchanged titles, just return valid
    if cal.size != 0 and cal[0].title == params[:calendar][:title]
      response = true
    else
      # Check both local and shared calendar names
      cals = Calendar.where(user_id: current_user.id, title: params[:calendar][:title])
      subs = Subscription.where(user_id: current_user.id, title: params[:calendar][:title])
      response = (cals.size == 0 and subs.size == 0)
    end
    respond_to do |format|
      format.json { render :json => response }
    end
  end

  private

    # Valaidte the user, making sure they own the calendar being accessed
    def correct_user
      @calendar = current_user.calendars.find_by_id(params[:id])
      redirect_to root_url if @calendar.nil?
    end

end

app/helpers/calendar_helper.rb
# The module is rails helper for displaying a calendar
# month view. 
# Author::    Mark Grebe  
# Developed for Master of Engineering Project
# University of Colorado - Boulder - Spring 2013
# Based on code by Ryan Bates from railscasts.com
module CalendarHelper
  def calendar(date = Time.zone.now.to_date, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Time.zone.now.to_date
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/helpers/calendars_helper.rb
# This module is a rails helper for setting display colors
# for calendars.
# Author::    Mark Grebe  
# Copyright:: Copyright (c) 2013 Mark Grebe
# License::   Distributes under the same terms as Ruby
# Developed for Master of Engineering Project
# University of Colorado - Boulder - Spring 2013
CALF_CLASS = Hash.new("calf_blue")
CALF_CLASS[0] = "calf_blue"
CALF_CLASS[1] = "calf_red"
CALF_CLASS[2] = "calf_orange"
CALF_CLASS[3] = "calf_yellow"
CALF_CLASS[4] = "calf_green"
CALF_CLASS[5] = "calf_purple"
CALF_CLASS[6] = "calf_brown"

CALB_CLASS = Hash.new("calb_blue")
CALB_CLASS[0] = "calb_blue"
CALB_CLASS[1] = "calb_red"
CALB_CLASS[2] = "calb_orange"
CALB_CLASS[3] = "calb_yellow"
CALB_CLASS[4] = "calb_green"
CALB_CLASS[5] = "calb_purple"
CALB_CLASS[6] = "calb_brown"

module CalendarsHelper
    def calf_class(calendar, user)
        if calendar.user_id == user.id
            if calendar.color.nil?
                return CALF_CLASS[0]
            else
                return CALF_CLASS[calendar.color.value]
            end
        else
            sub = Subscription.where("user_id = ? AND calendar_id = ?",
                    user.id, calendar.id)
            return CALF_CLASS[sub.first.color.value]
        end
    end

    def calb_class(calendar, user)
        if calendar.user_id == user.id
            if calendar.color.nil?
                return CALB_CLASS[0]
            else
                return CALB_CLASS[calendar.color.value]
            end
        else
            sub = Subscription.where("user_id = ? AND calendar_id = ?",
                    user.id, calendar.id)
            return CALB_CLASS[sub.first.color.value]
        end
    end

end

app/views/calendars/_calendar.html.erb
<li>
  <% if calendar.displayed.nil? or calendar.displayed %>
    <%= link_to calendar_path(calendar.id, displayed: false) do %>
    <i class="icon-check iconlink" id="check<%= calendar.id%>" ></i>
    <% end %>
  <% else %>
    <%= link_to calendar_path(calendar.id, displayed: true) do %>
    <i class="icon-check-empty iconlink" id="check<%= calendar.id%>" ></i>
    <% end %>
  <% end %>
  <i class="icon-circle <%= calf_class(calendar, @user) %>" ></i><%= calendar.title %>
  <span class="tooltip_class" data-toggle="tooltip" title="Calendar Settings">
  <%= link_to edit_calendar_path(calendar), :remote => true do %>
    <i class="icon-cogs iconlink"></i>
  <% end %>
  <span>
</li>

app/views/calendars/_calendar_form.html.erb
<div id="calendarModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <%= bootstrap_form_for(@calendar, remote: request.xhr?, :method => "put",
            html: { class: 'form-horizontal', id: 'calendar-form' }) do |f| %>
        <div class="modal-header">
            <button type="button" class="close pull-right" id="calendar_close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="calendar_model_title">Edit Calendar</h3>
        </div>
        <div class="modal-body">
            <div id="calendar_errorbox"><ul></ul></div>
            <%= f.text_field :title, value: "", label: 'Title' %>
            <%= f.text_area  :description, label: 'Description', :cols => 40, :rows => 3 %>
            <%= f.select :color, Calendar.color.options %>
            <%= f.control_group :public do %>
                <%= f.check_box :public, label: 'Make calendar read-only to everyone' %>
            <% end %>
        <div id="calendar_shared"></div>
        </div>
        <div class="modal-footer">
            <%= f.submit "Save", class: "btn btn-primary btn-cal pull-right" %>
         </div>
    <% end %>
</div>

app/views/calendars/_delete_btn.html.erb
<%= link_to "Delete", @calendar, method: :delete, :class => "btn calendar_delete_btn pull-left"%>

app/views/calendars/_share.html.erb
&emsp;&emsp;
<%= User.find(share.user_id).full_name %>
&nbsp;(<%= User.find(share.user_id).username %>)
&nbsp;
<% if share.rw? %>
(View and Modify)
<% else %>
(View Only)
<% end %>
&nbsp;
<%= link_to share, method: :put, remote: true do %>
<span class="tooltip_class" data-toggle="tooltip" title="Change Share Access">
<i class="icon-edit iconlink" id="change<%= share.id%>" ></i>
</span>
<% end %>
<%= link_to share, method: :delete, remote: true, data: { confirm: "You sure?" } do %>
<span class="tooltip_class" data-toggle="tooltip" title="Delete Share">
<i class="icon-trash iconlink" id="close<%= share.id%>" ></i>
</span>
<% end %>
<br>

app/views/calendars/_shares.html.erb
<% shares = Subscription.where(calendar_id: @calendar.id) %>
&emsp;<b>Shared With Users:</b>&nbsp;
<%= link_to '#shareModal', :id => "new_share", :data => {:toggle => "modal"} do %>
<span class="tooltip_class" data-toggle="tooltip" title="Add User">
<i class="icon-plus iconlink"></i>
<span>
<% end %>
<br>
<%= render partial: 'calendars/share', collection: shares %>

app/views/calendars/_subscribed_calendar.html.erb
<li>
  <% sub = subscription_for_cal_user(subscribed_calendar.id, @user.id) %>
  <% if sub.displayed? %>
    <%= link_to subscription_path(sub.id, displayed: false) do %>
    <i class="icon-check iconlink" id="check<%= subscribed_calendar.id%>" ></i>
    <% end %>
  <% else %>
    <%= link_to subscription_path(sub.id, displayed: true) do %>
    <i class="icon-check-empty iconlink" id="check<%= subscribed_calendar.id%>" ></i>
    <% end %>
  <% end %>
  <i class="icon-circle <%= calf_class(subscribed_calendar, @user) %>" ></i><%= sub.title %>
  <span class="tooltip_class" data-toggle="tooltip" title="Calendar Settings">
  <%= link_to edit_subscription_path(sub.id), :remote => true do %>
    <i class="icon-cogs iconlink"></i>
  <% end %>
</span>
</li>

app/views/calendars/edit.html.erb
<% provide(:title, 'Edit Calendar') %>

<h1>Edit Calendar</h1>
<%= render 'calendars/calendar_form' %>

app/views/calendars/edit.js.erb
$('#calendar_title').val("<%= @calendar.title %>");
$('#calendar_description').val("<%= @calendar.description %>");
$('#calendar_color').val("<%= @calendar.color %>");
$('#calendar-form').attr('action',"/calendars/<%= @calendar.id %>");
$('#calendar_model_title').text('Edit Calendar');
<% if @calendar.public %>
    $('#calendar_public').attr('checked', true);
<% else %>
    $('#calendar_public').attr('checked', false);
<% end %>
$('#calendar_shared').html("<%= j render('calendars/shares') %>")
$(document).ready(function(){ 
    $('.tooltip_class').tooltip();
    $('#new_share').click(function() {
        $('#subscription_username').val("");
    });
 });
$('#calendar_id').val("<%= @calendar.id %>")
$('.calendar_delete_btn').remove();
<% if !@calendar.default %>
$('.btn-cal').after('<%= j render(:partial => "calendars/delete_btn", :object => :calendar) %>');
<% end %>
$('#calendarModal').modal();

app/views/calendars/new.html.erb
<% provide(:title, 'Create New Calendar') %>

<h1>Create Calendar</h1>
<%= render 'calendars/calendar_form' %>