config/routes.rb
CalendarApp::Application.routes.draw do

  get "calendars/new"

  get "events/new"

  get "users/new"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :calendars
  resources :events, only: [:create, :edit, :update, :destroy]
  resources :subscriptions
 
  root to: 'static_pages#home'

  match '/events',  to: 'events#create'
  match '/calendars',  to: 'calendars#create'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/calendarcheck', to: 'calendars#check'
  match '/subscriptioncheck', to: 'subscriptions#check'
  match '/usercheck', to: 'users#check'
  match '/userverify', to: 'users#verify'
  match '/usersearch', to: 'users#search'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://cuengineeringonline.colorado.edu/coursedb/view-course/400">Master of Engineering Project</a>
    by Mark Grebe
  </small>
  <nav>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <% if signed_in? %>
        <%= link_to "Grebe Calendar App", user_path(current_user), id: "logo" %>
      <% else %>
        <%= link_to "Grebe Calendar App", root_path, id: "logo" %>
      <% end %>
      <nav>
        <% if params[:controller] == 'users' && params[:action] == 'show' %>
          <ul class="nav pull-left nav-pills">
            <% if @format == :month %>
              <li class="active">
            <% else %>
              <li>
            <% end %>
            <%= link_to "Month", current_url(:format => :month ) %></li>
            <% if @format == :week %>
              <li class="active">
            <% else %>
              <li>
            <% end %>
            <%= link_to "Week", current_url(:format => :week ) %></li>
            <% if @format == :day %>
              <li class="active">
            <% else %>
              <li>
            <% end %>
            <%= link_to "Day", current_url(:format => :day ) %></li>
            <% if @format == :list %>
              <li class="active">
            <% else %>
              <li>
            <% end %>
            <%= link_to "List", current_url(:format => :list ) %></li>
            <li>
            <li><%= link_to '#eventModal', :id => "new_event", :data => {:toggle => "modal"} do %>
                New Event
            <% end %></li>
          </ul>
        <% end %>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li><%= link_to user_path(current_user) do %>
              <i class="icon-home icon-white"></i>
            <% end %></li>
            <li id="fat-menu" class="dropdown">
              <%= link_to '#', class: "dropdown-toggle", :data => {:toggle => "dropdown"} do %>
                 <i class="icon-user icon-white"></i><b class="caret"></b>
              <% end %>
                <ul class="dropdown-menu">
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <% if current_user.admin? %>
                <li><%= link_to "Users", users_path %></li>
                <% end %>
                <li><%= link_to signout_path, method: "delete" do %>
                    Signout <i class="icon-off"></i>
                    <% end %></li>
              </ul>
            </li>
          <% else %>
             <% if params[:controller] != 'sessions' || params[:action] != 'new' %>
              <li><%= link_to "Sign In", signin_path %></li>
             <% end %>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>


 

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <%= render 'layouts/header' %>
      <div class="container">
        <% flash.each do |name, msg| %>
          <% if msg.is_a?(String) %>
            <div class="alert alert-<%= name %>">
              <a class="close" data-dismiss="alert">&#215;</a>
              <%= content_tag :div, msg, :id => "flash_#{name}" %>
            </div>
          <% end %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>